[package]
name = "cls"
version = "0.1.0"
edition = "2024"

[dependencies]
ratatui = { version = "0.29.0", features = ["all-widgets"] }
color-eyre = "0.6.2"
clap = { version = "4.4.2", features = ["derive"] }
ignore = "0.4.20"
rayon = "1.7.0"
anyhow = "1.0.75"
serde = { version = "1", features=["derive"] }
serde_json = "1"
tabled = "0.16"
tokei = "12.1"
